package com.dayang.uploadlib.model;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.dayang.uploadlib.model.MissionInfo;

import com.dayang.uploadlib.model.MissionInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig missionInfoDaoConfig;

    private final MissionInfoDao missionInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        missionInfoDaoConfig = daoConfigMap.get(MissionInfoDao.class).clone();
        missionInfoDaoConfig.initIdentityScope(type);

        missionInfoDao = new MissionInfoDao(missionInfoDaoConfig, this);

        registerDao(MissionInfo.class, missionInfoDao);
    }
    
    public void clear() {
        missionInfoDaoConfig.clearIdentityScope();
    }

    public MissionInfoDao getMissionInfoDao() {
        return missionInfoDao;
    }

}
